epigen_ucsd_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
#from nextseq_app import views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nextseq/', include('nextseq_app.urls')),
    path('setqc/', include('setqc_app.urls')),    
    path('metadata/', include('masterseq_app.urls')),
    path('manager/', include('manager_app.urls')),
    path('epigen/', include('collaborator_app.urls')),
    path('nextseq/login/', views.UserLoginView.as_view(), name='loginfromnexseq'),
    path('nextseq_app/login/', views.UserLoginView.as_view(),
         name='loginfromnexseq2'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('', views.UserLoginView.as_view(), name='login_from_base'),
    path('logout/', views.logout_view, name='logout'),
    path('changepassword/', views.change_password, name='change_password'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('singlecell/', include('singlecell_app.urls')),    
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

masterseq_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'masterseq_app'
urlpatterns = [
    path('index/', views.IndexView, name='index'),
    path('mymeta/', TemplateView.as_view(template_name="masterseq_app/metadata_user.html"), name='user_metadata'),
    path('samples/',views.SampleDataView, name='samples_display'),
    path('libs/',views.LibDataView, name='libs_display'),
    path('seqs/',views.SeqDataView, name='seqs_display'),
    path('usersamples/',views.UserSampleDataView, name='user_samples_display'),
    path('userlibs/',views.UserLibDataView, name='user_libs_display'),
    path('userseqs/',views.UserSeqDataView, name='user_seqs_display'),
    path('ajax/load-protocals/', views.load_protocals, name='ajax_load_protocals'),
    path('ajax/load-samples/', views.load_samples, name='ajax_load_samples'),
    path('ajax/load-libs/', views.load_libs, name='ajax_load_libs'),
    path('samples/adds/', views.SamplesCreateView, name='samples_add'),
    path('libraries/adds/', views.LibrariesCreateView, name='libraries_add'),
    path('seqs/adds/', views.SeqsCreateView, name='seqs_add'),
    path('sample/<int:pk>/delete/', views.SampleDeleteView, name='sample_delete'),
    path('lib/<int:pk>/delete/', views.LibDeleteView, name='lib_delete'),
    path('seq/<int:pk>/delete/', views.SeqDeleteView, name='seq_delete'),
    path('sample/<int:pk>/update/', views.SampleUpdateView, name='sample_update'),
    path('lib/<int:pk>/update/', views.LibUpdateView, name='lib_update'),
    path('seq/<int:pk>/update/', views.SeqUpdateView, name='seq_update'),
    path('sample/<int:pk>/', views.SampleDetailView, name='sample_detail'),
    path('lib/<int:pk>/', views.LibDetailView, name='lib_detail'),
    path('seq/<int:pk>/', views.SeqDetailView, name='seq_detail'),
    path('seq/<slug:seqid>/', views.SeqDetail2View, name='seq_detail_fromseqid'),
    path('savemymetadatatoexcel/', views.SaveMyMetaDataExcel, name='user_metadata_save_excel'),
    path('saveallmetadatatoexcel/', views.SaveAllMetaDataExcel, name='all_metadata_save_excel'),
    path('ajax/load-researchcontact/', views.load_researchcontact, name='ajax_load_researchcontact'),
    path('download/<path:path>/', views.download, name='download_from_db_folder'),
    path('bulkedit/', views.BulkUpdateView, name='bulk_update'),
    path('encodedataadd/', views.EncodeDataSaveView, name='encode_data_add'),



]

setqc_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'setqc_app'
urlpatterns = [

    path('', views.UserSetQCView, name='index'),
    path('mysets/', views.UserSetQCView, name='usersetqcs'),
    path('allsets/', views.AllSetQCView, name='allsetqcs'),
    path('adds/', views.SetQCCreateView, name='setqc_add'),
    path('<int:setqc_pk>/labelgenomeadds/', views.SetQCgenomelabelCreateView, name='libraylabelgenome_add'),
    path('<int:setqc_pk>/labelgenomeupdates/', views.SetQCgenomelabelUpdateView, name='libraylabelgenome_update'),
    path('<int:setqc_pk>/delete/', views.SetQCDeleteView, name='setqc_delete'),
    path('<int:setqc_pk>/update/',views.SetQCUpdateView, name='setqc_update'),
    path('<int:setqc_pk>/getmynotes/',views.GetNotesView, name='setqc_getnotes'),
    path('<int:setqc_pk>/runsetqc/',views.RunSetQC, name='runsetqc'),
    path('<int:setqc_pk>/runsetqc2/',views.RunSetQC2, name='runsetqc2'),
    path('<int:setqc_pk>/',views.SetQCDetailView, name='setqc_detail'),
    path('ajax/load-users/', views.load_users, name='ajax_load_users'),
    path('<int:setqc_pk>/<str:outputname>/web_summary.html', views.tenx_output, name='10xATACoutput'),

]

masterseq_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SampleCreationForm, LibraryCreationForm, SeqCreationForm,\
    SamplesCreationForm, LibsCreationForm, SeqsCreationForm, SeqsCreationForm,\
    LibsCreationForm_wetlab, SeqsCreationForm_wetlab, BulkUpdateForm, EncodeDataForm
from .models import SampleInfo, LibraryInfo, SeqInfo, ProtocalInfo, \
    SeqMachineInfo, SeqBioInfo, choice_for_preparation, choice_for_fixation,\
    choice_for_unit, choice_for_sample_type
from django.contrib.auth.models import User, Group
from nextseq_app.models import Barcode
from epigen_ucsd_django.shared import datetransform
from django.http import HttpResponse, JsonResponse
from django.db.models import Q
from epigen_ucsd_django.models import CollaboratorPersonInfo
import xlwt
from django.db.models import Prefetch
import re
import secrets
import string
from random import randint
from django.conf import settings
import os
from setqc_app.models import LibrariesSetQC
from singlecell_app.views import get_tenx_status, get_cooladmin_status, check_cooladmin_time, getReferenceUsed
from singlecell_app.models import CoolAdminSubmission
import subprocess
import datetime
from django.core.exceptions import PermissionDenied


def nonetolist(inputthing):
    if not inputthing:
        return []
    else:
        return inputthing


def removenone(inputlist):
    # remove None and duplicate value in inputlist, e.g. ['fe',None,'','gg'] to ['fe','gg']
    if not inputlist:
        return []
    else:
        y = [x for x in inputlist if x]
        return list(sorted(set(y), key=y.index))

def load_protocals(request):
    """ We did not use the ProtocalInfo in the later development, could consider removing this
    """
    exptype = request.GET.get('exptype')
    protocals = ProtocalInfo.objects.filter(
        experiment_type=exptype).order_by('protocal_name')
    print(protocals)
    return render(request, 'masterseq_app/protocal_dropdown_list_options.html', {'protocals': protocals})


@transaction.atomic
def BulkUpdateView(request):
    update_form = BulkUpdateForm(request.POST or None)
    i = 0
    titleinfo = {}
    colinfo = {}
    """
    The field name in template is not always the same with that in the model. 

    """
    title2field_seq = {
        'label (for qc report)': 'default_label',
        'team member intials': 'team_member_initails',
        'date submitted for sequencing': 'date_submitted_for_sequencing',
        'date': 'date_submitted_for_sequencing',
        'library id': 'libraryinfo',
        'sequening length': 'read_length',
        'read type': 'read_type',
        'portion of lane': 'portion_of_lane',
        'i7 index (if applicable)': 'i7index',
        'i5 index (or single index)': 'i5index',
        'notes': 'notes',
        'i7 index': 'i7index',
        'i5 index': 'i5index',
        'label': 'default_label',
        'sequencing length': 'read_length',
        'team member initials': 'team_member_initails',
    }
    title2field_lib = {
        'sample id (must match column i in sample sheet)': 'sampleinfo',
        'library description': 'library_description',
        'team member intials': 'team_member_initails',
        'date experiment started': 'date_started',
        'date experiment completed': 'date_completed',
        'experiment type': 'experiment_type',
        'protocol used': 'protocal_used',
        'reference to notebook and page number': 'reference_to_notebook_and_page_number',
        'notes': 'notes',
        'sample id': 'sampleinfo',
        'team member initials': 'team_member_initails',
    }
    title2field_sam = {
        'date': 'date',
        'sample description': 'description',
        'species': 'species',
        'sample type': 'sample_type',
        'preperation': 'preparation',
        'fixation?': 'fixation',
        'sample amount': 'sample_amount',
        'units': 'unit',
        'unit': 'unit',
        'service requested': 'service_requested',
        'sequencing depth to target': 'seq_depth_to_target',
        'sequencing length requested': 'seq_length_requested',
        'sequencing type requested': 'seq_type_requested',
        'notes': 'notes',
        'date sample received': 'date_received',
        'initials of reciever': 'team_member',
        'storage location': 'storage',
        'internal notes': 'internal_notes',
    }

    if update_form.is_valid():
        updateinfo = update_form.cleaned_data['updateinfo']
        for lineitem in updateinfo.strip().split('\n'):
            fields = lineitem.strip('\n').split('\t')
            if i == 0:
                for k in range(len(fields)):
                    titleinfo[k] = fields[k].strip().lower()
                    colinfo[k] = []

            else:
                for k in range(len(fields)):
                    colinfo[k].append(fields[k])
            i = i+1
        keytitle = titleinfo[0]
        if keytitle == 'sequencing id':
            cores_tm = {}
            machines_tm = {}
            for k in range(len(titleinfo)-1):
                if titleinfo[k+1] in ['team member intials', 'team member initials']:
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_seq = SeqInfo.objects.get(seq_id=item[0])
                        current_seq.team_member_initails = User.objects.get(
                            username=item[1].strip())
                        current_seq.save()
                elif titleinfo[k+1] in ['date submitted for sequencing', 'date']:
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_seq = SeqInfo.objects.get(seq_id=item[0])
                        current_seq.date_submitted_for_sequencing = datetransform(
                            item[1].strip())
                        current_seq.save()
                elif titleinfo[k+1] == 'library id':
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_seq = SeqInfo.objects.get(seq_id=item[0])
                        current_seq.libraryinfo = LibraryInfo.objects.get(
                            library_id=item[1].strip())
                        current_seq.save()
                elif titleinfo[k+1] == 'portion of lane':
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_seq = SeqInfo.objects.get(seq_id=item[0])
                        current_seq.portion_of_lane = float(item[1].strip())
                        current_seq.save()
                elif titleinfo[k+1] in ['i7 index (if applicable)', 'i7 index']:
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_seq = SeqInfo.objects.get(seq_id=item[0])
                        if item[1].strip():
                            current_seq.i7index = Barcode.objects.get(
                                indexid=item[1].strip())
                        else:
                            current_seq.i7index = None
                        current_seq.save()
                elif titleinfo[k+1] in ['i5 index (or single index)', 'i5 index']:
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_seq = SeqInfo.objects.get(seq_id=item[0])
                        if item[1].strip():
                            current_seq.i5index = Barcode.objects.get(
                                indexid=item[1].strip())
                        else:
                            current_seq.i5index = None
                        current_seq.save()
                elif titleinfo[k+1] not in ['sequencing core', 'sequening core', 'machine']:
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_seq = SeqInfo.objects.get(seq_id=item[0])
                        setattr(
                            current_seq, title2field_seq[titleinfo[k+1]], item[1].strip())
                        current_seq.save()
                else:
                    if titleinfo[k+1] in ['sequencing core', 'sequening core']:
                        cores_tm[colinfo[0]] = colinfo[k+1]
                    elif titleinfo[k+1] == 'machine':
                        machines_tm[colinfo[0]] = colinfo[k+1]
            for k in cores_tm.keys():
                current_seq = SeqInfo.objects.get(seq_id=k)
                current_seq.machine = SeqMachineInfo.objects.get(
                    sequencing_core=item[0], machine_name=item[1])
                current_seq.save()
        elif keytitle in ['library id (if library generated)', 'library id']:
            for k in range(len(titleinfo)-1):
                if titleinfo[k+1] in ['sample id (must match column i in sample sheet)', 'sample id']:
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_lib = LibraryInfo.objects.get(
                            library_id=item[0])
                        current_lib.sampleinfo = SampleInfo.objects.get(
                            sample_id=item[1].strip())
                        current_lib.save()
                elif titleinfo[k+1] in ['team member intials', 'team member initials']:
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_lib = LibraryInfo.objects.get(
                            library_id=item[0])
                        current_lib.team_member_initails = User.objects.get(
                            username=item[1].strip())
                        current_lib.save()
                elif titleinfo[k+1] == 'date experiment started':
                    for item in zip(colinfo[0], colinfo[k+1]):
                        current_lib = LibraryInfo.objects.get(
                            library_id=item[0])
                        current_lib.date_started = datetransform(

templates/masterseq_app/fiscalindex_dropdown_list_options.html
<option value="">---------</option>
{% for fis in fiscalindex %}
<option value="{{ fis.pk }}">{{fis.person.person_id.first_name}}&nbsp;{{fis.person.person_id.last_name}}__{{ fis.person.person_id.email }}__{{fis.index_name}}</option>
{% endfor %}

templates/masterseq_app/libraryadd.html
{% extends 'masterseq_app/base.html' %}

{% block content %}
{% load nextseq_app_tags %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <div class="card">
    <div class="card-header fortable">
      Add a new Library
    </div><!-- /.card-header -->
    <div class="card-body">
      {% if error_message %}
          <p class="error-message">{{ error_message }}</strong></p>
      {% endif %}
      <form id="librayspec" action="" method="post" data-protocal-url="{% url 'masterseq_app:ajax_load_protocals' %}">{% csrf_token %}  
        {% for field in library_form %}
        <div class="fieldWrapper">
          <p>
            <ul>
            {% for error in field.errors %}
            <li class="error-message" >
              {{error}}
            </li>
            {% endfor %}
            </ul>
            {% if field.field.widget|get_class == "Textarea" %}
            <p class="textarea">{{ field.label_tag }}</p>
               {{ field }}
            {% else %}
              {{ field.label_tag }} {{ field }}
            {% endif %}
            {% if field.help_text %}
            <span class="fontsize-sm" >{{ field.help_text|safe }}</span>
            {% endif %}
          </p>              
        </div>
        {% endfor %}   
        <input type="submit" value="Save"/>
      </form>
    </div><!-- /.card-body -->              
  </div><!-- /.card -->      
</div><!-- /#content --> 

{% endblock %}

templates/masterseq_app/researchcontact_dropdown_list_options.html
<option value="">---------</option>
{% for res in researchcontact %}
<option value="{{ res.pk }}">{{res.person_id.first_name}}&nbsp;{{res.person_id.last_name}}__{{ res.person_id.email }}__{{res.cell_phone}}</option>
{% endfor %}

templates/masterseq_app/sampledetail.html
{% extends 'masterseq_app/base.html' %}
{% block sidebar %}

<div class="col-sm-2 col-md-2 col-lg-2">
  <div class="fixed col-sm-2 col-md-2 col-lg-2">
  <div class="card checkboxsidebar" >
    <div class="card-header">
       Choose To Display
    </div>
    <div class="card-body">
      <ul class="list-group checkboxsidebar">
      <label class="list-group-item orange" name="summary">Summary</label>
      <!-- <label class="list-group-item orange" name="request">Service Request</label> -->
      <label class="list-group-item orange" name="libraries">Libraries</label>
      <label class="list-group-item orange" name="seqs">Seqs</label>       
      </ul>
    </div>
  </div>
  </div>
</div>
{% endblock %}
{% block content %}
{% load nextseq_app_tags %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% if 'my' in request.META.HTTP_REFERER or 'add' in request.META.HTTP_REFERER or 'update' in request.META.HTTP_REFERER%}
      <li class="breadcrumb-item"><a class="linkblue" href="{% url 'masterseq_app:user_metadata' %}">My Metadata</a></li>
      {% else %}
      <li class="breadcrumb-item"><a class="linkblue" href="{% url 'masterseq_app:index' %}">All Metadata</a></li>
      {% endif %}
      <li class="breadcrumb-item active" aria-current="page">Sample: {{ sampleinfo.sample_id }}</li>
    </ol>
  </nav>  

  {% include "masterseq_app/section_sample_summary.html"%}
  {% include "masterseq_app/section_sample_libraries.html"%}
  {% include "masterseq_app/section_sample_seqs.html"%}



</div><!-- /#content --> 



{% endblock %}

templates/masterseq_app/samplescollabsadd.html
{% extends 'masterseq_app/base.html' %}

{% block content %}
{% load nextseq_app_tags %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <div class="card">
    <div class="card-header fortable">
      Add 
    </div><!-- /.card-header -->
    <div class="card-body">
       <form id="groupdependent" action="" method="post" data-samplescollabs-url="{% url 'masterseq_app:ajax_load_researchcontact' %}" data-fiscalindex-url="{% url 'masterseq_app:ajax_load_fiscalindex' %}">{% csrf_token %}  
        {% for field in samplescollabs_form %}
        <div class="fieldWrapper">
          <p>
            <ul>
            {% for error in field.errors %}
            <li class="error-message" >
              {{error}}
            </li>
            {% endfor %}
            </ul>
            {% if field.field.widget|get_class == "Textarea" %}
            <p class="textarea">{{ field.label_tag }}</p>
               {{ field }}
            {% else %}
              {{ field.label_tag }} {{ field }}
            {% endif %}

            {% if field.help_text %}
            <span class="fontsize-sm" >{{ field.help_text|safe }}</span>
            {% endif %}
          </p>              
        </div>
        {% endfor %} 
        <button type="submit">Save</button>
      </form>
    </div><!-- /.card-body -->              
  </div><!-- /.card -->      
</div><!-- /#content --> 
{% endblock %}

templates/masterseq_app/section_sample_libraries.html
{% load nextseq_app_tags %}
{% load humanize %}
<div class="row" id="libraries">
  <div class="col-sm-12 col-md-12 col-lg-12">
    <div class="card bottom15">
      <div class="card-header fortable collapseheader">
        <a data-toggle="collapse" href="#collapse3" aria-expanded="true" aria-controls="collapse2"><i class="fa fas fa-caret-right collapseheader fa-lg fa-fw"></i><i class="fa fa-caret-down collapseheader fa-lg fa-fw"></i></a>
        Libraries
        <button type="button" class="close" aria-label="Close">
           <span aria-hidden="true">&times;</span>
        </button>
      </div><!-- /.card-header -->
      <div class="collapse show" id="collapse3">
        <div class="card-body">
          <br />
          <table class="table table-sm table-striped text-center table-responsive-xl">

            
            <thead>
            <tr>
              {% for x in libfield %}
              <th>{{ x }}</th>
              {% endfor %} 
            </tr>
            </thead>
            <tbody></tbody>

            {% for lib in libinfo %}
            <tr>
              {% for x in libfield %}
              <td>
                {% if x == 'library_id' %}
                <a href="{% url 'masterseq_app:lib_detail' lib.pk %}">{{ lib|get_value:x|default_if_none:"" }}</a>
                {% else %}
                {{ lib|get_value:x|default_if_none:"" }}
                {% endif %}
            </td>
              {% endfor %}
            </tr>
            {% endfor %}
            </tbody>               
          </table>
        </div><!-- /.card-body --> 
      </div><!-- /.collapse -->             
    </div><!-- /.card -->
  
  </div>
</div>

templates/masterseq_app/section_seq_setqc.html
{% load nextseq_app_tags %}
{% load humanize %}
<div class="row" id="relatedsetqc">
  <div class="col-sm-12 col-md-12 col-lg-12">
    <div class="card bottom15">
      <div class="card-header fortable collapseheader">
        <a data-toggle="collapse" href="#collapse3" aria-expanded="true" aria-controls="collapse3"><i class="fa fas fa-caret-right collapseheader fa-lg fa-fw"></i><i class="fa fa-caret-down collapseheader fa-lg fa-fw"></i></a>
        SetQC
        <button type="button" class="close" aria-label="Close">
           <span aria-hidden="true">&times;</span>
        </button>
      </div><!-- /.card-header -->
      <div class="collapse show" id="collapse3">
        <div class="card-body">
          <br />
          <table class="table table-sm table-striped text-center table-responsive-xl">

            
            <thead>
            <tr>
              {% for x in setqcfield %}
              <th>{{ x }}</th>
              {% endfor %} 
            </tr>
            </thead>
            <tbody></tbody>

            {% for setqc in setqcs %}
            <tr>
              {% for x in setqcfield %}
                {% if x == 'set_name' %}
                  <td><a href="{% url 'setqc_app:setqc_detail' setqc.pk %}">{{ setqc|get_value:x|default_if_none:"" }}</a></td>
                {% elif x == 'url' %}
                  <td><a href="{{setqc.url}}" target="_blank"><i class="fas fa-file-alt" style="font-size: 17px;color:#26D07C"></i></a></td>
                {% else %}
                  <td>{{ setqc|get_value:x|default_if_none:"" }}</td>
                {% endif %}
              {% endfor %}
            </tr>
            {% endfor %}
            </tbody>               
          </table>
        </div><!-- /.card-body --> 
      </div><!-- /.collapse -->             
    </div><!-- /.card -->
  
  </div>
</div>

templates/masterseq_app/seqdetail.html
{% extends 'masterseq_app/base.html' %}
{% block sidebar %}

<div class="col-sm-2 col-md-2 col-lg-2">
  <div class="fixed col-sm-2 col-md-2 col-lg-2">
    <div class="card checkboxsidebar">
      <div class="card-header">
        Choose To Display
      </div>
      <div class="card-body">
        <ul class="list-group checkboxsidebar">
          <label class="list-group-item orange" name="summary">Summary</label>
          <label class="list-group-item orange" name="seqbioinfo">Seq Bioinfomatics</label>
          <label class="list-group-item orange" name="relatedsetqc">SetQC</label>
          <label class="list-group-item orange" name="singlecell_section">Single Cell</label>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
{% load nextseq_app_tags %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% if 'my' in request.META.HTTP_REFERER or 'add' in request.META.HTTP_REFERER or 'update' in request.META.HTTP_REFERER%}
      <li class="breadcrumb-item"><a class="linkblue" href="{% url 'masterseq_app:user_metadata' %}">My Metadata</a>
      </li>
      {% else %}
      <li class="breadcrumb-item"><a class="linkblue" href="{% url 'masterseq_app:index' %}">All Metadata</a></li>
      {% endif %}
      <li class="breadcrumb-item active" aria-current="page">Seq: {{ seqinfo.seq_id }}</li>
    </ol>
  </nav>

  {% include "masterseq_app/section_seq_summary.html"%}
  {% include "masterseq_app/section_seq_bioinfo.html"%}
  {% include "masterseq_app/section_seq_setqc.html"%}
  {% include "masterseq_app/section_seq_singlecell.html"%}


</div><!-- /#content -->



{% endblock %}

templates/masterseq_app/seqsaddconfirm.html
{% extends 'masterseq_app/base.html' %}

{% block sidebar %}
<div id="sidebar" class="col-sm-2 col-md-2 col-lg-2" role="navigation">
  <div class="list-group navsiebar">
    <li class="sidebar-header">MetaData App</li>
    <a href="{% url 'masterseq_app:sample_add' %}" class="list-group-item list-group-item-action-custom-green editable">Add a new sample</a> 
    <a href="{% url 'masterseq_app:library_add' %}" class="list-group-item list-group-item-action-custom-green ">Add a new library</a>
    <a href="{% url 'masterseq_app:seq_add' %}" class="list-group-item list-group-item-action-custom-green">Add new seqs</a>
    <a href="{% url 'masterseq_app:samples_add' %}" class="list-group-item list-group-item-action-custom-green editable">Add new samples</a> 
    <a href="{% url 'masterseq_app:libraries_add' %}" class="list-group-item list-group-item-action-custom-green ">Add new libraries</a>
    <a href="{% url 'masterseq_app:seqs_add' %}" class="list-group-item list-group-item-action-custom-green active ">Add new seqs</a>     
  </div>
</div> 
{% endblock %}

{% block content %}
{% load nextseq_app_tags %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <div class="card">
    <div class="card-header fortable">
      Check the genome and label for each library
    </div><!-- /.card-header -->
    <div class="card-body bigtoppadcardbody">
      {% if error_message %}
          <p class="error-message">{{ error_message }}</strong></p>
      {% endif %}
      <form action="" method="post">{% csrf_token %}  
        <table id="labelgenomecreatetable" class="table table-striped table-sm">
        {{ formsetcustom.management_form }}  
        {% for form in formsetcustom.forms %}
          {% if forloop.first %}
          <thead>
            <tr>
            {% for field in form.visible_fields %}
            <th>{{ field.label|capfirst }}</th>
            {% endfor %}
            </tr>
          </thead>
          {% endif %}
             <tr>
               {% for field in form.visible_fields %}
                  <td class="align-middle">
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                      <span class="error-message" >{{ form.non_field_errors.as_ul }}</span>
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}
                    {% endif %}
                    <span class="error-message" >{{ field.errors.as_ul }}</span>
              
                    {{ field }}
                  </td>
                {% endfor %}
             </tr>
        {% endfor %}
        </table>
        <input type="submit" value="Save"/>
      </form>
    </div><!-- /.card-body -->              
  </div><!-- /.card -->      
</div><!-- /#content --> 

{% endblock %}