collaborator_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.urls import path, include

app_name = 'collaborator_app'
urlpatterns = [
    path('metadata/mymeta/', TemplateView.as_view(template_name="collaborator_app/collab_metadata_user.html"), name='user_metadata'),
    path('metadata/usersamples/',views.UserSampleDataView, name='user_samples_display'),
    path('metadata/userlibs/',views.UserLibDataView, name='user_libs_display'),
    path('metadata/userseqs/',views.UserSeqDataView, name='user_seqs_display'),    
    path('setqc/mysets/', TemplateView.as_view(template_name="collaborator_app/collab_setqc_user.html"), name='usersetqcs'),
    path('setqc/<int:setqc_pk>/getmynotes/',views.CollaboratorGetNotesView, name='setqc_getnotes'),
    #path('userscseqs', views.UserSingleCellSeqs, name='user_scseqs_display'),
    path('myprofile/',views.UserProfileView, name='user_profile'),  

    path('singlecell/ajax/getSeqs', views.CollaboratorSingleCellData, name='get_seqs'),
    path('singlecell/MySeqs', views.singlecell_view, name='myseqs'),
    path('setqc/usersetqcs/',views.UserSetqcView, name='user_setqcs_display'),

    path('changepassword/', views.collab_change_password, name='collab_change_password'),
    path('setqc/myreports/', views.CollaboratorSetQCView, name='collaboratorsetqcs'),
    path('setqc//<int:setqc_pk>/details/',views.CollaboratorSetQCDetailView, name='setqc_collaboratordetail'),
    path('setqc/<int:setqc_pk>/getnotes/',views.CollaboratorGetNotesView, name='setqc_collaboratorgetnotes'),
    path('mysamples/', views.CollaboratorSampleView, name='collab_samples'),
    path('mysamples_com/', views.CollaboratorSampleComView, name='collab_samples_compare'),
    path('feeforservice/servicerequest/', views.ServiceRequestListView, name='collab_servicerequest_list'),
    path('feeforservice/servicerequest_add/', views.ServiceRequestCreateView, name='collab_servicerequest_add'),

]

epigen_ucsd_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
#from nextseq_app import views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nextseq/', include('nextseq_app.urls')),
    path('setqc/', include('setqc_app.urls')),    
    path('metadata/', include('masterseq_app.urls')),
    path('manager/', include('manager_app.urls')),
    path('epigen/', include('collaborator_app.urls')),
    path('nextseq/login/', views.UserLoginView.as_view(), name='loginfromnexseq'),
    path('nextseq_app/login/', views.UserLoginView.as_view(),
         name='loginfromnexseq2'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('', views.UserLoginView.as_view(), name='login_from_base'),
    path('logout/', views.logout_view, name='logout'),
    path('changepassword/', views.change_password, name='change_password'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('singlecell/', include('singlecell_app.urls')),    
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

masterseq_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'masterseq_app'
urlpatterns = [
    path('index/', views.IndexView, name='index'),
    path('mymeta/', TemplateView.as_view(template_name="masterseq_app/metadata_user.html"), name='user_metadata'),
    path('samples/',views.SampleDataView, name='samples_display'),
    path('libs/',views.LibDataView, name='libs_display'),
    path('seqs/',views.SeqDataView, name='seqs_display'),
    path('usersamples/',views.UserSampleDataView, name='user_samples_display'),
    path('userlibs/',views.UserLibDataView, name='user_libs_display'),
    path('userseqs/',views.UserSeqDataView, name='user_seqs_display'),
    path('ajax/load-protocals/', views.load_protocals, name='ajax_load_protocals'),
    path('ajax/load-samples/', views.load_samples, name='ajax_load_samples'),
    path('ajax/load-libs/', views.load_libs, name='ajax_load_libs'),
    path('samples/adds/', views.SamplesCreateView, name='samples_add'),
    path('libraries/adds/', views.LibrariesCreateView, name='libraries_add'),
    path('seqs/adds/', views.SeqsCreateView, name='seqs_add'),
    path('sample/<int:pk>/delete/', views.SampleDeleteView, name='sample_delete'),
    path('lib/<int:pk>/delete/', views.LibDeleteView, name='lib_delete'),
    path('seq/<int:pk>/delete/', views.SeqDeleteView, name='seq_delete'),
    path('sample/<int:pk>/update/', views.SampleUpdateView, name='sample_update'),
    path('lib/<int:pk>/update/', views.LibUpdateView, name='lib_update'),
    path('seq/<int:pk>/update/', views.SeqUpdateView, name='seq_update'),
    path('sample/<int:pk>/', views.SampleDetailView, name='sample_detail'),
    path('lib/<int:pk>/', views.LibDetailView, name='lib_detail'),
    path('seq/<int:pk>/', views.SeqDetailView, name='seq_detail'),
    path('seq/<slug:seqid>/', views.SeqDetail2View, name='seq_detail_fromseqid'),
    path('savemymetadatatoexcel/', views.SaveMyMetaDataExcel, name='user_metadata_save_excel'),
    path('saveallmetadatatoexcel/', views.SaveAllMetaDataExcel, name='all_metadata_save_excel'),
    path('ajax/load-researchcontact/', views.load_researchcontact, name='ajax_load_researchcontact'),
    path('download/<path:path>/', views.download, name='download_from_db_folder'),
    path('bulkedit/', views.BulkUpdateView, name='bulk_update'),
    path('encodedataadd/', views.EncodeDataSaveView, name='encode_data_add'),



]

setqc_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'setqc_app'
urlpatterns = [

    path('', views.UserSetQCView, name='index'),
    path('mysets/', views.UserSetQCView, name='usersetqcs'),
    path('allsets/', views.AllSetQCView, name='allsetqcs'),
    path('adds/', views.SetQCCreateView, name='setqc_add'),
    path('<int:setqc_pk>/labelgenomeadds/', views.SetQCgenomelabelCreateView, name='libraylabelgenome_add'),
    path('<int:setqc_pk>/labelgenomeupdates/', views.SetQCgenomelabelUpdateView, name='libraylabelgenome_update'),
    path('<int:setqc_pk>/delete/', views.SetQCDeleteView, name='setqc_delete'),
    path('<int:setqc_pk>/update/',views.SetQCUpdateView, name='setqc_update'),
    path('<int:setqc_pk>/getmynotes/',views.GetNotesView, name='setqc_getnotes'),
    path('<int:setqc_pk>/runsetqc/',views.RunSetQC, name='runsetqc'),
    path('<int:setqc_pk>/runsetqc2/',views.RunSetQC2, name='runsetqc2'),
    path('<int:setqc_pk>/',views.SetQCDetailView, name='setqc_detail'),
    path('ajax/load-users/', views.load_users, name='ajax_load_users'),
    path('<int:setqc_pk>/<str:outputname>/web_summary.html', views.tenx_output, name='10xATACoutput'),

]

collaborator_app/forms.py
from django import forms
from .models import ServiceInfo,ServiceRequest,ServiceRequestItem

class ServiceRequestItemCreationForm(forms.ModelForm):
    class Meta:
        model = ServiceRequestItem
        fields = ['service', 'quantity']
class ServiceRequestCreationForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['notes']
        widgets = {
            'notes': forms.Textarea(attrs={'cols': 60, 'rows': 3}),
        }

collaborator_app/views.py
from django.shortcuts import redirect,render,get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from epigen_ucsd_django.shared import is_in_multiple_groups
from django.http import JsonResponse
from setqc_app.models import LibrariesSetQC,LibraryInSet
from masterseq_app.models import SampleInfo
from singlecell_app.views import build_seq_list, SINGLE_CELL_EXPS
from epigen_ucsd_django.models import CollaboratorPersonInfo,Group_Institution
from django.core import serializers
from masterseq_app.models import SampleInfo, LibraryInfo, SeqInfo, ProtocalInfo, \
    SeqMachineInfo
from django.contrib.auth.models import User, Group
from setqc_app.models import LibrariesSetQC, LibraryInSet
from .forms import ServiceRequestItemCreationForm,ServiceRequestCreationForm
import datetime
from django.forms import formset_factory
from django.db import transaction
# Create your views here.

DisplayFieldforcollab = ['set_name','date_requested','experiment_type','url']


def UserSampleDataView(request):
    group_name = request.user.groups.all().first().name
    print(group_name)

    Samples_list = SampleInfo.objects.filter(group=request.user.groups.all().first()).values(
        'pk', 'sample_id', 'description', 'date', 'sample_type', 'group__name', 'status')
    for sample in Samples_list:
        try:
            sample['group__name'] = sample['group__name'].replace(
                '_group', '').replace('_', ' ')
        except:
            pass
    data = list(Samples_list)

    return JsonResponse(data, safe=False)


def UserLibDataView(request):
    # Libs_list = LibraryInfo.objects.filter(team_member_initails=request.user)\
    #     .select_related('sampleinfo__group').values(
    #         'pk', 'library_description','library_id', 'sampleinfo__id',  'sampleinfo__sample_type', 'sampleinfo__sample_id', 'sampleinfo__description',
    #     'sampleinfo__species', 'sampleinfo__group__name', 'date_started', 'experiment_type')
    Libs_list = LibraryInfo.objects.select_related('sampleinfo__group').filter(sampleinfo__group=request.user.groups.all().first()).values(
            'pk', 'library_description','library_id', 'sampleinfo__id',  'sampleinfo__sample_type', 'sampleinfo__sample_id', 'sampleinfo__description',
        'sampleinfo__species', 'sampleinfo__group__name', 'date_started', 'experiment_type')
    data = list(Libs_list)

    return JsonResponse(data, safe=False)


def UserSeqDataView(request):
    # Seqs_list = SeqInfo.objects.filter(team_member_initails=request.user)\
    #     .select_related('libraryinfo__sampleinfo__group','machine').values(
    #     'pk', 'seq_id','libraryinfo__library_description', 'libraryinfo__sampleinfo__id', 'libraryinfo__sampleinfo__sample_id',
    #     'libraryinfo__sampleinfo__description', 'libraryinfo__sampleinfo__group__name',
    #     'date_submitted_for_sequencing','machine__sequencing_core',\
    #     'machine__machine_name','portion_of_lane','read_length', 'read_type')
    Seqs_list = SeqInfo.objects.select_related('libraryinfo__sampleinfo__group','machine').filter(libraryinfo__sampleinfo__group=request.user.groups.all().first()).values(
        'pk', 'seq_id','libraryinfo__library_description', 'libraryinfo__sampleinfo__id', 'libraryinfo__sampleinfo__sample_id',
        'libraryinfo__sampleinfo__description', 'libraryinfo__sampleinfo__group__name',
        'date_submitted_for_sequencing','machine__sequencing_core',\
        'machine__machine_name','portion_of_lane','read_length', 'read_type')
    data = list(Seqs_list)

    return JsonResponse(data, safe=False)


def UserSetqcView(request):

    Setqcs_list = LibrariesSetQC.objects.filter(group=request.user.groups.all().first()).values(
        'pk','notes','set_id','set_name','last_modified','experiment_type','url','status')
    data = list(Setqcs_list)

    return JsonResponse(data, safe=False)

def CollaboratorGetNotesView(request,setqc_pk):
    setinfo = get_object_or_404(LibrariesSetQC, pk=setqc_pk)
    if setinfo.collaborator != request.user:
        raise PermissionDenied
    data = {}
    data['notes'] = setinfo.notes
    return JsonResponse(data)

def GetNotesView(request, setqc_pk):
    setinfo = get_object_or_404(LibrariesSetQC, pk=setqc_pk)
    # if setinfo.requestor != request.user and not request.user.groups.filter(name='bioinformatics').exists():
    #     raise PermissionDenied
    data = {}
    data['notes'] = setinfo.notes
    return JsonResponse(data)

def UserProfileView(request):
    group = request.user.groups.all().first()
    collabs = CollaboratorPersonInfo.objects.filter(group=group).select_related('person_id').prefetch_related('person_id__groups')
    collabs_list = collabs.values(\
        'group__name',\
        'person_id__first_name','person_id__last_name',\
        'phone','email','role','index','initial_password')
    group_institute_list = Group_Institution.objects.all().select_related('group').values('group__name','institution')
    group_institute_dict = {}
    for item in group_institute_list:
        group_institute_dict[item['group__name']]=item['institution']
 
    context = {
        'user_name':request.user.username,
        'group_name': group.name,
        'collab_list':collabs_list,
        'group_institute_dict':group_institute_dict,
    }

    return render(request, 'collaborator_app/collab_user_profile.html', context)   


def collab_change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, form.user)
            #messages.success(request, 'Your password was successfully updated!')

            return redirect('collaborator_app:user_metadata')

        # else:
            #messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'collaborator_app/collaborator_change_password.html', {
        'form': form
    })
def CollaboratorSetQCView(request):
    SetQC_list = LibrariesSetQC.objects.filter(collaborator=request.user)
    context = {
        'Sets_list': SetQC_list,
        'DisplayField':DisplayFieldforcollab,
    }
    return render(request, 'collaborator_app/collaboratorsetqcinfo.html', context)





def CollaboratorSetQCDetailView(request,setqc_pk):
    setinfo = get_object_or_404(LibrariesSetQC, pk=setqc_pk)
    if setinfo.collaborator != request.user:
        raise PermissionDenied
    summaryfield = ['set_name','collaborator','date_requested','requestor','experiment_type','notes','url','version']
    groupinputinfo = ''
    librariesset = LibraryInSet.objects.filter(librariesetqc=setinfo)
    list1tem = list(librariesset.values_list('seqinfo', flat=True))
    list1 = [SeqInfo.objects.values_list('seq_id', flat=True).get(id=x)
     for x in list1tem]
    if setinfo.experiment_type == 'ChIP-seq':
        list2 = list(librariesset.values_list('group_number', flat=True))
        list3 = list(librariesset.values_list('is_input', flat=True))
        groupinputinfo = list(zip(list1,list2,list3))
    context = {
        'setinfo':setinfo,
        'summaryfield':summaryfield,
        'libraryinfo': list1,
        'groupinputinfo':groupinputinfo,
    }
    return render(request, 'collaborator_app/collaboratordetails.html', context=context)

def CollaboratorSampleView(request):
	collab_person = CollaboratorPersonInfo.objects.get(person_id=request.user)
	Sample_list = SampleInfo.objects.filter(research_person=collab_person).values(\
		'pk','sample_id','date','sample_type','service_requested','status')
	data=list(Sample_list)

	return JsonResponse(data,safe=False)

def CollaboratorSampleComView(request):
	collab_person = CollaboratorPersonInfo.objects.get(person_id=request.user)
	SetQC_list = LibrariesSetQC.objects.filter(collaborator=request.user)
	Sample_list = SampleInfo.objects.filter(research_person=collab_person).values(\
		'pk','sample_id','date','sample_type','service_requested','status')
	context = {
		'Sets_list': SetQC_list,
		'DisplayField':DisplayFieldforcollab,
		'Sample_list':Sample_list,
	}
	return render(request, 'collaborator_app/collaboratorsetqcinfocom.html', context)


def ServiceRequestListView(request):

    context = {

    }
    return render(request, 'collaborator_app/collab_feeforservice_quote.html', context)

@transaction.atomic
def ServiceRequestCreateView(request):

    data_requestitem = {}
    data_request = {}

    ServiceRequestItemFormSet = formset_factory(
        ServiceRequestItemCreationForm, can_delete=True)
    servicerequestitems_formset = ServiceRequestItemFormSet(request.POST or None)
    groupinfo = request.user.groups.all().first()
    today = datetime.date.today()

    if request.method == 'POST':
        servicerequest_form = ServiceRequestCreationForm(request.POST)
        if servicerequest_form.is_valid():
            data_request = {
                'date':str(today),
                'group':groupinfo.name,
                'status':'initiate',
                'notes':servicerequest_form.cleaned_data['notes'],
            }
            if servicerequestitems_formset.is_valid():
                for form in servicerequestitems_formset.forms:
                    if form not in servicerequestitems_formset.deleted_forms and form.cleaned_data:
                        service = form.cleaned_data['service']
                        quantity = form.cleaned_data['quantity']
                        data_requestitem[service.service_name] = {
                            'rate':str(service.uc_rate)+'/'+service.rate_unit,
                            'rate_number':service.uc_rate,
                            'quantity':quantity,
                        }
                total_price = sum([float(x['rate_number'])*float(x['quantity']) for x in data_requestitem.values()])

templates/collaborator_app/collab_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>Epigen</title>
  {% endblock %}

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% load static %}
  {% load nextseq_app_tags %}

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
    integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css"
    integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.2.7/css/select.dataTables.min.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?v=1.0.94" />



</head>

<body>

  <div id="wrapper">
    {% block navheader %}
    <nav class="navbar navbar-expand-lg navbar-default navbar-light bg-light fixed-top borderline">
      <a class="navbar-brand" href="#"><img alt="Charisma Logo" src="{% static 'images/CFE_Brandmark-01.png' %}"
          class="crop" margin="-200px 0 -200px 0" width=auto height=50 /></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a id="feeforservice" class="nav-link" href="{% url 'collaborator_app:collab_servicerequest_list' %}">
              FeeForService </a>
          </li>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item">
            <a id="metadata" class="nav-link" href="{% url 'collaborator_app:user_metadata' %}"> MetaData </a>
          </li>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item">
            <a id="setqc" class="nav-link" href="{% url 'collaborator_app:usersetqcs' %}"> SetQC </a>
          </li>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item">
            <a id="singlecell" class="nav-link" href="{% url 'collaborator_app:myseqs' %}"> SingleCell </a>
          </li>
        </ul>


        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'collaborator_app:user_profile' %}"><i class="fas fa-id-card"></i>
                User Profile</a>
              <a class="dropdown-item" href="{% url 'change_password' %}"><i class="fas fa-key"></i> PasswordChange</a>
              <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% endblock %}

    <div class="container-fluid">
      <div class="row">
        {% block sidebar %}
        {% endblock %}
        {% block content %}
        {% endblock %}
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div><!-- /#wrapper -->


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/select/1.2.7/js/dataTables.select.min.js"></script>

  <script src="{% static 'js/jquery.formset.js' %}"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
    integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
  <script src="{% static 'js/epigen.js' %}?v=1.0.94"></script>


</body>


</html>

templates/collaborator_app/collab_feeforservice_base.html
{% extends 'collaborator_app/collab_base.html' %}

{% block title %}
<title>FeeForServiceApp</title>
{% endblock %}

{% block sidebar %}
<div id="sidebar" class="col-sm-2 col-md-2 col-lg-2" role="navigation">
  <div class="list-group navsiebar">
    <li class="sidebar-header">FeeForService App</li>
    <a href="{% url 'collaborator_app:collab_servicerequest_list' %}" class="list-group-item list-group-item-action-custom editable">My ServiceRequest</a>
    <a href="{% url 'collaborator_app:collab_servicerequest_add' %}" class="list-group-item list-group-item-action-custom">Add a new ServiceRequest</a>
    <a href="" class="list-group-item list-group-item-action-custom">Service Intro</a>

 
  </div>
</div> 

{% endblock %}

{% block content %}
{% endblock %}

templates/collaborator_app/collab_metadata_user.html
{% extends 'collaborator_app/collab_metadata_base.html' %}

{% block content %}
{% load nextseq_app_tags %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active linkblue" data-toggle="tab" href="#mysample" role="tab">My Samples</a>
    </li>
    <li class="nav-item">
      <a class="nav-link linkblue" data-toggle="tab" href="#mylibs" role="tab">My Libs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link linkblue" data-toggle="tab" href="#myseqs" role="tab">My Seqs</a>
    </li>
    <li class="ml-auto rpadding-2">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle linkblue" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <i class="fas fa-download"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'masterseq_app:user_metadata_save_excel' %}">Save My Metadata to Excel</a>
          </div>
        </li>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade  show active" id="mysample" role="tabpanel">
        <div class="card-body"  >
          <table id="collab_metadata_samples" data-href="{% url 'collaborator_app:user_samples_display'%}" class="table table-striped table-hover table-sm text-left table-responsive-xl" width="100%">
            <thead>
              <tr>
                <th scope="col">sample_name</th>
                <th scope="col">description</th>
                <th scope="col">date</th>
                <th scope="col">group</th>
                <th scope="col">sample_type</th>               
                <th scope="col">status</th>
              </tr>
            </thead>
          </table>
        </div><!-- /.card-body -->              
      </div>      
  

      <div class="tab-pane fade" id="mylibs" role="tabpanel">
        <div class="card-body">
          <table id="collab_metadata_libs" data-href="{% url 'collaborator_app:user_libs_display'%}" class="table table-striped table-hover table-sm text-left table-responsive-xl" width="100%">
            <thead>
              <tr>
                <th scope="col">library_id</th>
                <th scope="col">library_description</th>
                <th scope="col">sample_name</th>
                <th scope="col">sample_type</th>
                <th scope="col">sample_description</th>
                <th scope="col">species</th>		
                <th scope="col">group</th>
                <th scope="col">date</th>
                <th scope="col">experiment_type</th>
              </tr>
            </thead>
          </table>
        </div><!-- /.card-body -->              
      </div><!-- /.tab-pane -->      

      <div class="tab-pane fade" id="myseqs" role="tabpanel">
        <div class="card-body">
          <table id="collab_metadata_seqs" data-href="{% url 'collaborator_app:user_seqs_display'%}" class="table table-striped table-hover table-sm text-left table-responsive-xl" width="100%">
            <thead>
              <tr>
                <th scope="col">seq_id</th>
                <th scope="col">library_description</th>
                <th scope="col">sample_name</th>
                <th scope="col">sample_description</th>
                <th scope="col">group</th>
                <th scope="col">date_submitted_for_sequencing</th>
                <th scope="col">sequencing_machine</th>
                <th scope="col">portion_of_lane</th>
                <th scope="col">read_length</th>
                <th scope="col">read_type</th>
              </tr>
            </thead>
          </table>
        </div><!-- /.card-body -->              
      </div><!-- /.tab-pane -->  
     </div>
</div><!-- /#content -->

{% endblock %}