epigen_ucsd_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
#from nextseq_app import views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nextseq/', include('nextseq_app.urls')),
    path('setqc/', include('setqc_app.urls')),    
    path('metadata/', include('masterseq_app.urls')),
    path('manager/', include('manager_app.urls')),
    path('epigen/', include('collaborator_app.urls')),
    path('nextseq/login/', views.UserLoginView.as_view(), name='loginfromnexseq'),
    path('nextseq_app/login/', views.UserLoginView.as_view(),
         name='loginfromnexseq2'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('', views.UserLoginView.as_view(), name='login_from_base'),
    path('logout/', views.logout_view, name='logout'),
    path('changepassword/', views.change_password, name='change_password'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('singlecell/', include('singlecell_app.urls')),    
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

masterseq_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'masterseq_app'
urlpatterns = [
    path('index/', views.IndexView, name='index'),
    path('mymeta/', TemplateView.as_view(template_name="masterseq_app/metadata_user.html"), name='user_metadata'),
    path('samples/',views.SampleDataView, name='samples_display'),
    path('libs/',views.LibDataView, name='libs_display'),
    path('seqs/',views.SeqDataView, name='seqs_display'),
    path('usersamples/',views.UserSampleDataView, name='user_samples_display'),
    path('userlibs/',views.UserLibDataView, name='user_libs_display'),
    path('userseqs/',views.UserSeqDataView, name='user_seqs_display'),
    path('ajax/load-protocals/', views.load_protocals, name='ajax_load_protocals'),
    path('ajax/load-samples/', views.load_samples, name='ajax_load_samples'),
    path('ajax/load-libs/', views.load_libs, name='ajax_load_libs'),
    path('samples/adds/', views.SamplesCreateView, name='samples_add'),
    path('libraries/adds/', views.LibrariesCreateView, name='libraries_add'),
    path('seqs/adds/', views.SeqsCreateView, name='seqs_add'),
    path('sample/<int:pk>/delete/', views.SampleDeleteView, name='sample_delete'),
    path('lib/<int:pk>/delete/', views.LibDeleteView, name='lib_delete'),
    path('seq/<int:pk>/delete/', views.SeqDeleteView, name='seq_delete'),
    path('sample/<int:pk>/update/', views.SampleUpdateView, name='sample_update'),
    path('lib/<int:pk>/update/', views.LibUpdateView, name='lib_update'),
    path('seq/<int:pk>/update/', views.SeqUpdateView, name='seq_update'),
    path('sample/<int:pk>/', views.SampleDetailView, name='sample_detail'),
    path('lib/<int:pk>/', views.LibDetailView, name='lib_detail'),
    path('seq/<int:pk>/', views.SeqDetailView, name='seq_detail'),
    path('seq/<slug:seqid>/', views.SeqDetail2View, name='seq_detail_fromseqid'),
    path('savemymetadatatoexcel/', views.SaveMyMetaDataExcel, name='user_metadata_save_excel'),
    path('saveallmetadatatoexcel/', views.SaveAllMetaDataExcel, name='all_metadata_save_excel'),
    path('ajax/load-researchcontact/', views.load_researchcontact, name='ajax_load_researchcontact'),
    path('download/<path:path>/', views.download, name='download_from_db_folder'),
    path('bulkedit/', views.BulkUpdateView, name='bulk_update'),
    path('encodedataadd/', views.EncodeDataSaveView, name='encode_data_add'),



]

nextseq_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'nextseq_app'
urlpatterns = [

    path('', views.IndexView, name='index'),
    path('myruns/', views.IndexView, name='userruns'),
    path('mysamples/', views.UserSamplesView, name='usersamples'),
    path('allruns/', views.AllRunsView, name='allruns'),
    path('allsamples/', views.AllSamplesView, name='allsamples'),
    path('<int:pk>/', views.RunDetailView2.as_view(), name='rundetail'),
    path('adds/', views.RunCreateView4, name='runandsample_add'),
    path('addsinbulky/', views.RunCreateView6, name='runandsample_add_inbulky'),
    path('<slug:username>/<int:run_pk>/update/',
         views.RunUpdateView2, name='run_update'),
    path('<int:run_pk>/delete2/', views.RunDeleteView2, name='run_delete2'),
    path('<int:run_pk>/samplesheetcreate/',
         views.SampleSheetCreateView, name='samplesheet_create'),
    path('<int:run_pk>/demultiplexing/',
         views.DemultiplexingView, name='demultiplexing'),
    path('<int:run_pk>/demultiplexing2/',
         views.DemultiplexingView2, name='demultiplexing2'),
    path('<int:run_pk>/downloadingfromigm/',
         views.DownloadingfromIGM, name='downloadingfromigm'),
]

setqc_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'setqc_app'
urlpatterns = [

    path('', views.UserSetQCView, name='index'),
    path('mysets/', views.UserSetQCView, name='usersetqcs'),
    path('allsets/', views.AllSetQCView, name='allsetqcs'),
    path('adds/', views.SetQCCreateView, name='setqc_add'),
    path('<int:setqc_pk>/labelgenomeadds/', views.SetQCgenomelabelCreateView, name='libraylabelgenome_add'),
    path('<int:setqc_pk>/labelgenomeupdates/', views.SetQCgenomelabelUpdateView, name='libraylabelgenome_update'),
    path('<int:setqc_pk>/delete/', views.SetQCDeleteView, name='setqc_delete'),
    path('<int:setqc_pk>/update/',views.SetQCUpdateView, name='setqc_update'),
    path('<int:setqc_pk>/getmynotes/',views.GetNotesView, name='setqc_getnotes'),
    path('<int:setqc_pk>/runsetqc/',views.RunSetQC, name='runsetqc'),
    path('<int:setqc_pk>/runsetqc2/',views.RunSetQC2, name='runsetqc2'),
    path('<int:setqc_pk>/',views.SetQCDetailView, name='setqc_detail'),
    path('ajax/load-users/', views.load_users, name='ajax_load_users'),
    path('<int:setqc_pk>/<str:outputname>/web_summary.html', views.tenx_output, name='10xATACoutput'),

]

nextseq_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

choice_for_machine = (
    ('EPIGEN_NextSeq550', 'EPIGEN_NextSeq550'),
    ('IGM_HiSeq4000', 'IGM_HiSeq4000'),
    ('IGM_NovaSeq', 'IGM_NovaSeq'),
)


class Barcode(models.Model):
    indexid = models.CharField(max_length=200, unique=True)
    indexseq = models.CharField(max_length=200)
    kit_choice = (('BK', 'bulk'), ('S2', 'snATAC_v2'),
                  ('TA', '10xATAC'), ('TR', '10xRNA'),
                  ('BT', 'bulk_10xATAC'),('TM','10x_mix_RNA_ATAC'))
    kit = models.CharField(
        max_length=2, choices=kit_choice, default='BK', help_text='bulk (default), snATAC_v2:combinatory barcode v2, 10xATAC, 10xRNAseq')

    def __str__(self):
        return self.indexid

    class Meta:
        ordering = ['indexid']


class RunInfo(models.Model):
    # runid = models.CharField(max_length=200,unique=True,help_text='Please enter the flowcellSe')
    Flowcell_ID = models.CharField(
        max_length=200, unique=True, help_text='Please enter the FlowcellSerialNumber, like H5GLYBGX5')
    operator = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField('I did this run on...',
                            help_text='If the datepicker is not working, please enter in this form: yyyy-mm-dd, like 2018-04-03', blank=True, null=True)
    read_type_choice = (('SE', 'Single-end'), ('PE', 'Paired-end'))
    exp_type_choice = (('BK', 'bulk'), ('S2', 'snATAC_v2'),
                       ('TA', '10xATAC'), ('TR', '10xRNA'), ('BT', 'bulk_10xATAC'),('TM','10x_mix_RNA_ATAC'))
    read_type = models.CharField(
        max_length=2, choices=read_type_choice, default='PE', help_text='default:PE')
    experiment_type = models.CharField(max_length=2, choices=exp_type_choice,
                                       default='BK', help_text='bulk (default), snATAC_v2:combinatory barcode v2, 10xATAC, 10xRNAseq, bulk_10xATAC, 10x_mix_RNA_ATAC')
    total_reads = models.BigIntegerField(blank=True, null=True)
    total_libraries = models.IntegerField(blank=True, null=True)
    percent_of_reads_demultiplexed = models.IntegerField(blank=True, null=True)
    read_length = models.CharField(
        max_length=50, help_text='Bulk: one number(eg. 75); Single-cell: R1+I1+I2+R2 (eg:50+8+16+50)')
    updated_at = models.DateTimeField(auto_now=True)
    nextseqdir = models.CharField(max_length=200, blank=True, null=True)
    # machine = models.ForeignKey('masterseq_app.SeqMachineInfo', on_delete=models.CASCADE, null=True)
    machine = models.CharField(
        max_length=50, choices=choice_for_machine, default='EPIGEN_NextSeq550', null=True)
    total_lanes = models.FloatField(blank=True, null=True)
    extra_parameters = models.TextField(
        blank=True, help_text='Default: blank; or like "--use-bases-mask Y50,I8n*,Y16,Y50"')
    jobstatus = models.CharField(
        max_length=200, blank=True, null=True, default='ClickToSubmit')

    def get_absolute_url(self):
        return reverse('nextseq_app:rundetail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.Flowcell_ID

    class Meta:
        ordering = ['-date']


class LibrariesInRun(models.Model):
    singlerun = models.ForeignKey(RunInfo, on_delete=models.CASCADE)
    Library_ID = models.CharField(max_length=200, unique=True)
    i7index = models.ForeignKey(Barcode, related_name='i7_index',
                                on_delete=models.CASCADE, blank=True, null=True)
    i5index = models.ForeignKey(Barcode, related_name='i5_index',
                                on_delete=models.CASCADE, blank=True, null=True)
    numberofreads = models.IntegerField(blank=True, null=True)
    lane = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.Library_ID

    class Meta:
        ordering = ['Library_ID']

nextseq_app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
#from django.utils.translation import gettext_lazy as _
from .models import RunInfo, LibrariesInRun
from django.forms import ModelForm

# class DateInput(forms.DateInput):
# 	input_type = 'date'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']
        help_texts = {
            'username': '',
            'password1': '',
            'password2': ''
        }


class UserLoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RunCreationForm(ModelForm):
    class Meta:
        model = RunInfo
        fields = ['Flowcell_ID', 'date', 'read_type',
                  'read_length', 'experiment_type', 'machine','total_lanes','extra_parameters']
        widgets = {
            'date': forms.DateInput(),
            'experiment_type': forms.Select(attrs={'id': 'nextseq_app_experiment_type'}),
            'machine': forms.Select(attrs={'id': 'nextseq_app_machine'}),
            'extra_parameters': forms.Textarea(attrs={'cols': 60, 'rows': 1}),
            # 'read_type': forms.TextInput(attrs={'class': 'myfieldclass'}),
        }
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['machine'].queryset = SeqMachineInfo.objects.filter(sequencing_core__in=['EPIGEN','IGM'])



class LibrariesInRunForm(ModelForm):
    class Meta:
        model = LibrariesInRun
        fields = ['Library_ID', 'i7index', 'i5index']


class SamplesToCreatForm(forms.Form):
    samplestocreat = forms.CharField(
        label='Libraries to Save:',
        widget=forms.Textarea(attrs={'cols': 60, 'rows': 20}),
        initial='Sequencing_ID i7index i5index lane(separated by Space or Tab)\n'
    )

templates/nextseq_app/base.html
{% extends 'common/base.html' %}

  {% block title %}
  <title>SeqManager</title>
  {% endblock %}

{% block sidebar %}
{% load static %}
<div id="sidebar" class="col-sm-2 col-md-2 col-lg-2" role="navigation">
  <div class="list-group navsiebar">
    <li class="sidebar-header">SeqManager App</li>
    <a href="{% url 'nextseq_app:userruns' %}" class="list-group-item list-group-item-action-custom editable">My Runs</a>      
    <a href="{% url 'nextseq_app:usersamples' %}" class="list-group-item list-group-item-action-custom" >My Libraries</a>      
    <a href="{% url 'nextseq_app:runandsample_add_inbulky' %}" class="list-group-item list-group-item-action-custom">Add a Run</a>
    <a href="{% url 'nextseq_app:allruns' %}" class="list-group-item list-group-item-action-custom">All Runs</a>      
    <a href="{% url 'nextseq_app:allsamples' %}" class="list-group-item list-group-item-action-custom" >All Libraries</a>
  </div>
  <br>
<div>
<a class="list-group-item-action-custom-hide" data-toggle="collapse" href="#collapsecalendar" aria-expanded="false"><img src="{% static 'images/icons8-calendar-512.png' %}"  alt="Machine Scheduler" width="30" height="30"/><span>NextSeq/Sony Sorter</span></a>
</div>
  <div class="list-group navsiebar collapse" id="collapsecalendar">
    <br>
  <div class="googleCalendar">
    <iframe src="https://calendar.google.com/calendar/embed?showPrint=0&amp;showTz=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffcc33&amp;src=n8ovlcimmbn0acoc44li7bc0u8%40group.calendar.google.com&amp;color=%237A367A&amp;ctz=America%2FLos_Angeles" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
  </div>
  <br>
  <div class="googleCalendar">
    <iframe src="https://calendar.google.com/calendar/embed?showPrint=0&amp;showTz=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffcc33&amp;src=65nstmgo42luajull3n3ajte60%40group.calendar.google.com&amp;color=%237A367A&amp;ctz=America%2FLos_Angeles" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
  </div>
</div>


</div> 

{% endblock %}

{% block content %}
{% endblock %}

templates/nextseq_app/details.html
{% extends 'nextseq_app/base.html' %}
{% block sidebar %}

<div class="col-sm-2 col-md-2 col-lg-2">
  <div class="fixed col-sm-2 col-md-2 col-lg-2">
  <div class="card checkboxsidebar" >
    <div class="card-header">
       Choose To Display
    </div>
    <div class="card-body">
      <ul class="list-group checkboxsidebar">
      <label class="list-group-item" name="summary">Summary</label>
      <label class="list-group-item" name="libraries">Libraries</label>
        
      </ul>
    </div>
  </div>
  </div>
</div>
{% endblock %}
{% block content %}
{% load nextseq_app_tags %}
{% load humanize %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% if 'my' in request.META.HTTP_REFERER %}
      <li class="breadcrumb-item"><a class="linkblue" href="{% url 'nextseq_app:userruns' %}">My Runs</a></li>
      {% else %}
      <li class="breadcrumb-item"><a class="linkblue" href="{% url 'nextseq_app:allruns' %}">Runs</a></li>
      {% endif %}
      <li class="breadcrumb-item active" aria-current="page">{{ runinfo.Flowcell_ID }}</li>
    </ol>
  </nav>  

  {% include "nextseq_app/runsummary.html"%}
  {% include "nextseq_app/runlibraries.html"%}

</div><!-- /#content --> 



{% endblock %}

templates/nextseq_app/runsinfo_bio.html
{% extends 'nextseq_app/base.html' %}

{% block content %}
{% load nextseq_app_tags %}
{% load humanize %}

<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <div class="card">
    <div class="card-header fortable">
      All Runs
    </div><!-- /.card-header -->
    <div class="card-body">
      <table class="table table-striped table-sm datatablesort2 text-center table-responsive-xl">
        <thead>
          <tr>
            <th scope="col">Flowcell</th>
            <th scope="col">Operator</th>
            <th scope="col">Date</th>
            <th scope="col">Read Type</th>
            <th scope="col">Read Length</th>
            <th scope="col">Total libraries</th>
            <th scope="col">Total lanes</th>
            <th scope="col">Total reads</th>
            <th scope="col">%demultiplexed</th>	    	    
            <th scope="col">Last Modified</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for Run in RunInfo_list %}
          <tr>        
            <td><a id="flowcell-{{Run.Flowcell_ID}}" href="{% url 'nextseq_app:rundetail' Run.pk %}"> {{ Run.Flowcell_ID }} </a></td>
            <td>{{ Run.operator }}</td>
            <td id="date-{{Run.Flowcell_ID}}">{{ Run.date|date:"Y-m-d" }}</td>
            <td>{{ Run.read_type }}</td>
            <td>{{ Run.read_length }}</td>
            <td>{{ Run.total_libraries | default_if_none:""}}</td>
            <td>{{ Run.total_lanes | default_if_none:""}}</td>
       	    <td>{{ Run.total_reads | default_if_none:"" | intcomma }}</td>
		<td>  <div class="progress">
		    <div class="progress-bar" role="progressbar" aria-valuenow={{Run.percent_of_reads_demultiplexed}} aria-valuemin="0" aria-valuemax="100" style="width:{{ Run.percent_of_reads_demultiplexed| default_if_none:""|percentage}}">
            {{ Run.percent_of_reads_demultiplexed| default_if_none:""|percentage }}
	  </div></td>
            <td>{{ Run.updated_at|date:"m/d/Y H:i" }}</td>
            {% if Run.jobstatus == 'Done'%}
            <td><span class="badge badge-success badge-status-green">Done</span></td>
            {% elif Run.jobstatus == 'ClickToSubmit' %}
              {% if Run.machine == 'IGM_HiSeq4000' or Run.machine == 'IGM_NovaSeq' %}
              <td><a class="btn btn-danger btn-sm btn-status-orange downloadajax" href="" data-toggle="modal" data-target="#downloadModal" data-href="{% url 'nextseq_app:downloadingfromigm' Run.id %}"
                id={{Run.Flowcell_ID}}>ClickToTransfer</a></td>
              {% else %}
              <td><a class="btn btn-danger btn-sm btn-status-orange dmpajax" href="" data-href="{% url 'nextseq_app:demultiplexing' Run.id %}" id={{Run.Flowcell_ID}}>ClickToDemultiplex</a></td>
               {% endif %}
            {% elif Run.jobstatus == 'JobSubmitted'%}
            <td><span class="badge badge-success badge-status-blue">JobSubmitted</span></td>
            {% elif Run.jobstatus == 'JobStarted'%}
            <td><span class="badge badge-success badge-status-lightblue">JobStarted</span></td>
            {% elif Run.jobstatus == 'Error'%}
            <td><span class="badge badge-success badge-status-yellow">Error</span></td>
            {% elif Run.jobstatus == 'Warning'%}
            <td><span class="badge badge-success badge-status-yellow" data-toggle="tooltip" data-placement="right" title="contain libraries with reads number less than 1000">Warning</span></td>
            {% endif %}
            <td>
              <a class="spacing" href="{% url 'nextseq_app:run_update' username=user.username run_pk=Run.id %}"><i class="fas fa-edit"></i></a>
              <a onclick="return confirm('Are you sure you want to delete {{ Run.Flowcell_ID }} ?');" href="{% url 'nextseq_app:run_delete2' Run.id %}"><i class="fas fa-trash-alt"></i></a>                
            </td>
          </tr>
          {% empty %}
          <li>No Runs yet.</li>
          {% endfor %}
        </tbody>
      </table>
    </div><!-- /.card-body -->              
  </div><!-- /.card -->      
</div><!-- /#content --> 


<!-- Modal -->
<div class="modal fade" id="downloadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Please supply the info from igm's email:</h5>

      </div>
      <div class="modal-body">
      <form id="downloadingform" action="" method="post">{% csrf_token %}  
        <input class="modalinput" type="text" name="downloadaddress" size="100" placeholder="Ftp address"><br><br>
        <input class="modalinput" type="text" name="username" size="100" placeholder="Username"><br><br>
        <input class="modalinput" type="password" name="pass" size="100" placeholder="Password"><br><br>
      </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn confirm-btn-orange" id="submitForm">Confirm</button>
      </div>
    </div>
  </div>
</div>  
{% endblock %}

templates/nextseq_app/userrunsinfo.html
{% extends 'nextseq_app/base.html' %}

{% block content %}
{% load nextseq_app_tags %}
{% load humanize %}

<div id="content" class="col-sm-10 col-md-10 col-lg-10">
  <div class="card">
    <div class="card-header fortable">
      My Runs
    </div><!-- /.card-header -->
    <div class="card-body">
      <table class="table table-striped table-sm datatablesort2 text-center table-responsive-xl">
        <thead>
          <tr>
            <th scope="col">Flowcell</th>
            <th scope="col">Operator</th>
            <th scope="col">Date</th>
            <th scope="col">Read Type</th>
            <th scope="col">Read Length</th>
            <th scope="col">Total libraries</th>
            <th scope="col">Total lanes</th>
            <th scope="col">Total reads</th>
            <th scope="col">%demultiplexed</th>	    	    
            <th scope="col">Last Modified</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for Run in RunInfo_list %}
          <tr>                
            <td><a id="flowcell-{{Run.Flowcell_ID}}" href="{% url 'nextseq_app:rundetail' Run.pk %}"> {{ Run.Flowcell_ID }} </a></td>
            <td>{{ Run.operator }}</td>
            <td id="date-{{Run.Flowcell_ID}}">{{ Run.date|date:"Y-m-d" }}</td>
            <td>{{ Run.read_type }}</td>
            <td>{{ Run.read_length }}</td>
            <td>{{ Run.total_libraries | default_if_none:""}}</td>
            <td>{{ Run.total_lanes | default_if_none:""}}</td>
            <td>{{ Run.total_reads | default_if_none:"" | intcomma}}</td>
		<td>  <div class="progress">
		    <div class="progress-bar" role="progressbar" aria-valuenow={{Run.percent_of_reads_demultiplexed}} aria-valuemin="0" aria-valuemax="100" style="width:{{ Run.percent_of_reads_demultiplexed| default_if_none:""| percentage}}">
            {{ Run.percent_of_reads_demultiplexed| default_if_none:""|percentage }}
	  </div></td>
            <td>{{ Run.updated_at|date:"m/d/Y H:i" }}</td>
            {% if Run.jobstatus == 'Done'%}
            <td><span class="badge badge-success badge-status-green">Done</span></td>
            {% elif Run.jobstatus == 'ClickToSubmit' %}
              {% if Run.machine == 'IGM_HiSeq4000' or Run.machine == 'IGM_NovaSeq' %}
              <td><a class="btn btn-danger btn-sm btn-status-orange downloadajax" href="" data-toggle="modal" data-target="#downloadModal" data-href="{% url 'nextseq_app:downloadingfromigm' Run.id %}"
                id={{Run.Flowcell_ID}}>ClickToTransfer</a></td>
              {% else %}
              <td><a class="btn btn-danger btn-sm btn-status-orange dmpajax" href="" data-href="{% url 'nextseq_app:demultiplexing' Run.id %}" id={{Run.Flowcell_ID}}>ClickToDemultiplex</a></td>
              {% endif %}
            {% elif Run.jobstatus == 'JobSubmitted'%}
            <td><span class="badge badge-success badge-status-blue">JobSubmitted</span></td>
            {% elif Run.jobstatus == 'JobStarted'%}
            <td><span class="badge badge-success badge-status-lightblue">JobStarted</span></td>
            {% elif Run.jobstatus == 'Error'%}
            <td><span class="badge badge-success badge-status-yellow">Error</span></td>
            {% elif Run.jobstatus == 'Warning'%}
            <td><span class="badge badge-success badge-status-yellow" data-toggle="tooltip" data-placement="right" title="contain libraries with reads number less than 1000">Warning</span></td>
            {% endif %}
            <td>
              <a class="spacing" href="{% url 'nextseq_app:run_update' username=user.username run_pk=Run.id %}"><i class="fas fa-edit"></i></a>
              <a onclick="return confirm('Are you sure you want to delete {{ Run.Flowcell_ID }} ?');" href="{% url 'nextseq_app:run_delete2' Run.id %}"><i class="fas fa-trash-alt"></i></a>                
            </td>
          </tr>
          {% empty %}
          <li>No Runs yet.</li>
          {% endfor %}
        </tbody>
      </table>

    </div><!-- /.card-body -->
  </div><!-- /.card -->
</div><!-- /#content --> 

<!-- Modal -->
<div class="modal fade" id="downloadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Please supply the info from igm's email:</h5>

      </div>
      <div class="modal-body">
      <form id="downloadingform" action="" method="post">{% csrf_token %}  
        <input class="modalinput" type="text" name="downloadaddress" size="100" placeholder="Ftp address"><br><br>
        <input class="modalinput" type="text" name="username" size="100" placeholder="Username"><br><br>
        <input class="modalinput" type="password" name="pass" size="100" placeholder="Password"><br><br>
      </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn confirm-btn-orange" id="submitForm">Confirm</button>
      </div>
    </div>
  </div>
</div>   
{% endblock %}