collaborator_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.urls import path, include

app_name = 'collaborator_app'
urlpatterns = [
    path('metadata/mymeta/', TemplateView.as_view(template_name="collaborator_app/collab_metadata_user.html"), name='user_metadata'),
    path('metadata/usersamples/',views.UserSampleDataView, name='user_samples_display'),
    path('metadata/userlibs/',views.UserLibDataView, name='user_libs_display'),
    path('metadata/userseqs/',views.UserSeqDataView, name='user_seqs_display'),    
    path('setqc/mysets/', TemplateView.as_view(template_name="collaborator_app/collab_setqc_user.html"), name='usersetqcs'),
    path('setqc/<int:setqc_pk>/getmynotes/',views.CollaboratorGetNotesView, name='setqc_getnotes'),
    #path('userscseqs', views.UserSingleCellSeqs, name='user_scseqs_display'),
    path('myprofile/',views.UserProfileView, name='user_profile'),  

    path('singlecell/ajax/getSeqs', views.CollaboratorSingleCellData, name='get_seqs'),
    path('singlecell/MySeqs', views.singlecell_view, name='myseqs'),
    path('setqc/usersetqcs/',views.UserSetqcView, name='user_setqcs_display'),

    path('changepassword/', views.collab_change_password, name='collab_change_password'),
    path('setqc/myreports/', views.CollaboratorSetQCView, name='collaboratorsetqcs'),
    path('setqc//<int:setqc_pk>/details/',views.CollaboratorSetQCDetailView, name='setqc_collaboratordetail'),
    path('setqc/<int:setqc_pk>/getnotes/',views.CollaboratorGetNotesView, name='setqc_collaboratorgetnotes'),
    path('mysamples/', views.CollaboratorSampleView, name='collab_samples'),
    path('mysamples_com/', views.CollaboratorSampleComView, name='collab_samples_compare'),
    path('feeforservice/servicerequest/', views.ServiceRequestListView, name='collab_servicerequest_list'),
    path('feeforservice/servicerequest_add/', views.ServiceRequestCreateView, name='collab_servicerequest_add'),

]

epigen_ucsd_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
#from nextseq_app import views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nextseq/', include('nextseq_app.urls')),
    path('setqc/', include('setqc_app.urls')),    
    path('metadata/', include('masterseq_app.urls')),
    path('manager/', include('manager_app.urls')),
    path('epigen/', include('collaborator_app.urls')),
    path('nextseq/login/', views.UserLoginView.as_view(), name='loginfromnexseq'),
    path('nextseq_app/login/', views.UserLoginView.as_view(),
         name='loginfromnexseq2'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('', views.UserLoginView.as_view(), name='login_from_base'),
    path('logout/', views.logout_view, name='logout'),
    path('changepassword/', views.change_password, name='change_password'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('singlecell/', include('singlecell_app.urls')),    
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

masterseq_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'masterseq_app'
urlpatterns = [
    path('index/', views.IndexView, name='index'),
    path('mymeta/', TemplateView.as_view(template_name="masterseq_app/metadata_user.html"), name='user_metadata'),
    path('samples/',views.SampleDataView, name='samples_display'),
    path('libs/',views.LibDataView, name='libs_display'),
    path('seqs/',views.SeqDataView, name='seqs_display'),
    path('usersamples/',views.UserSampleDataView, name='user_samples_display'),
    path('userlibs/',views.UserLibDataView, name='user_libs_display'),
    path('userseqs/',views.UserSeqDataView, name='user_seqs_display'),
    path('ajax/load-protocals/', views.load_protocals, name='ajax_load_protocals'),
    path('ajax/load-samples/', views.load_samples, name='ajax_load_samples'),
    path('ajax/load-libs/', views.load_libs, name='ajax_load_libs'),
    path('samples/adds/', views.SamplesCreateView, name='samples_add'),
    path('libraries/adds/', views.LibrariesCreateView, name='libraries_add'),
    path('seqs/adds/', views.SeqsCreateView, name='seqs_add'),
    path('sample/<int:pk>/delete/', views.SampleDeleteView, name='sample_delete'),
    path('lib/<int:pk>/delete/', views.LibDeleteView, name='lib_delete'),
    path('seq/<int:pk>/delete/', views.SeqDeleteView, name='seq_delete'),
    path('sample/<int:pk>/update/', views.SampleUpdateView, name='sample_update'),
    path('lib/<int:pk>/update/', views.LibUpdateView, name='lib_update'),
    path('seq/<int:pk>/update/', views.SeqUpdateView, name='seq_update'),
    path('sample/<int:pk>/', views.SampleDetailView, name='sample_detail'),
    path('lib/<int:pk>/', views.LibDetailView, name='lib_detail'),
    path('seq/<int:pk>/', views.SeqDetailView, name='seq_detail'),
    path('seq/<slug:seqid>/', views.SeqDetail2View, name='seq_detail_fromseqid'),
    path('savemymetadatatoexcel/', views.SaveMyMetaDataExcel, name='user_metadata_save_excel'),
    path('saveallmetadatatoexcel/', views.SaveAllMetaDataExcel, name='all_metadata_save_excel'),
    path('ajax/load-researchcontact/', views.load_researchcontact, name='ajax_load_researchcontact'),
    path('download/<path:path>/', views.download, name='download_from_db_folder'),
    path('bulkedit/', views.BulkUpdateView, name='bulk_update'),
    path('encodedataadd/', views.EncodeDataSaveView, name='encode_data_add'),



]

setqc_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'setqc_app'
urlpatterns = [

    path('', views.UserSetQCView, name='index'),
    path('mysets/', views.UserSetQCView, name='usersetqcs'),
    path('allsets/', views.AllSetQCView, name='allsetqcs'),
    path('adds/', views.SetQCCreateView, name='setqc_add'),
    path('<int:setqc_pk>/labelgenomeadds/', views.SetQCgenomelabelCreateView, name='libraylabelgenome_add'),
    path('<int:setqc_pk>/labelgenomeupdates/', views.SetQCgenomelabelUpdateView, name='libraylabelgenome_update'),
    path('<int:setqc_pk>/delete/', views.SetQCDeleteView, name='setqc_delete'),
    path('<int:setqc_pk>/update/',views.SetQCUpdateView, name='setqc_update'),
    path('<int:setqc_pk>/getmynotes/',views.GetNotesView, name='setqc_getnotes'),
    path('<int:setqc_pk>/runsetqc/',views.RunSetQC, name='runsetqc'),
    path('<int:setqc_pk>/runsetqc2/',views.RunSetQC2, name='runsetqc2'),
    path('<int:setqc_pk>/',views.SetQCDetailView, name='setqc_detail'),
    path('ajax/load-users/', views.load_users, name='ajax_load_users'),
    path('<int:setqc_pk>/<str:outputname>/web_summary.html', views.tenx_output, name='10xATACoutput'),

]

singlecell_app/urls.py
from django.urls import path
from . import views

app_name = 'singlecell_app'
urlpatterns = [
    path('AllSeqs', views.AllSeqs, name='allseqs'),
    path('MySeqs', views.MySeqs, name='myseqs'),
    path('all_singlecell_data/', views.AllSingleCellData,
         name='all_singlecell_data'),
    path('user_singlecell_data/', views.UserSingleCellData,
         name='user_singlecell_data'),
    path('all_10xATAC_QC_data/', views.All10xAtacQcData,
         name='all_10xATAC_QC_data'),
    path('user_10xATAC_QC_data/', views.User10xAtacQcData,
         name='user_10xATAC_QC_data'),
    path('all_10xRNA_QC_data/', views.All10xRnaQcData, name='all_10xRNA_QC_data'),
    path('user_10xRNA_QC_data/', views.User10xRnaQcData,
         name='user_10xRNA_QC_data'),
    path('EditCoolAdmin/<str:seqinfo>',
         views.edit_cooladmin_sub, name='editcooladmin'),
    path('ajax/submitcooladmin/', views.submit_cooladmin, name='submitcooladmin'),
    path('ajax/submit/', views.submit_singlecell, name='submitsinglecell'),
    path('ajax/generate_link', views.generate_tenx_link, name='generate_link'),
    path('websummary/<str:seq_id>', views.view_websummary, name="view_websummart"),

]

singlecell_app/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
# Create your models here.


class CoolAdminSubmission(models.Model):
    V6 = 'v6'
    V4 = 'v4'
    V2 = 'v2'
    pipeline_versions_choices = [
        (V2, 'v2'),
        (V4, 'v4'),
        (V6, 'v6')
    ]

    submitted = models.BooleanField(default=False)
    pipeline_status = models.CharField(max_length=20, default='ClickToSubmit')
    pipeline_version = models.CharField(
        max_length=2, choices=pipeline_versions_choices, default=V6)
    seqinfo = models.ForeignKey(
        'masterseq_app.SeqInfo', on_delete=models.CASCADE, blank=False, null=True)
    refgenome = models.CharField(max_length=10, blank=True, null=True)
    date_submitted = models.DateTimeField(blank=True, null=True)
    date_modified = models.DateTimeField(blank=True, null=True)
    ''' Optional Parameters to be included later'''
    # USEHARMONY (default False, true if set to True) Perform harmony batch correction using the dataset IDs as batch IDs (Only used with 10x_model_multiple_projects.bash)
    useHarmony = models.BooleanField(default=False)

    # SNAPUSEPEAK (default False, true if set to True) Construct a peak matrix in addition to the bin matrix
    snapUsePeak = models.BooleanField(default=False)
    # SNAPSUBSET default empty or 0. Should be interger). Use this number to construct a subset that is used to construct the distance matrix for SNAP. The lower it is, the lesser is the resolution. After 10-15K cells, the memory might become an issue
    snapSubset = models.PositiveIntegerField(default=0)
    # DOCHROMVAR (default False, true if set to True). Perform chromVAR analysis
    doChromVar = models.BooleanField(default=False)
    # READINPEAK (default empty or default value: 0. Should be 0 < float < 1). QC metric used to filter cells with low ratio of reads in peak
    readInPeak = models.FloatField(default=0)
    # TSSPERCELL (default empty or default value: 7. Should be float ). QC metric used to filter cells with low TSS
    tssPerCell = models.FloatField(default=7)
    # MINNBREADPERCELL (default empty or default value: 500. Should be int ). QC metric used to filter cells with low number of aligned fragments
    minReadPerCell = models.IntegerField(default=500)
    # SNAPBINSIZE (default empty or default value: 5000 100000. Should be a list of int values separated by a blank). Determine the bins used to perform SNAP clustering.
    snapBinSize = models.CharField(default='5000 100000', max_length=100)
    # SNAPNDIMS (default empty or default value: 25. Should be a list of int values separated by a blank). Determine the number of dimensions to use to perform SNAP clustering.
    snapNDims = models.CharField(default="25", max_length=100)
    # link for cooladmin portal
    link = models.CharField(max_length=280, blank=True, null=True)


class CommonQCInfo(models.Model):
    estimated_cell_count = models.PositiveIntegerField()

    class Meta:
        abstract = True


class scRNAqcInfo(models.Model):
    estimated_number_of_cells = models.PositiveIntegerField()
    mean_reads_per_cell = models.PositiveIntegerField()
    median_genes_per_cell = models.PositiveIntegerField()
    number_of_reads = models.PositiveIntegerField()
    valid_barcodes = models.DecimalField(max_digits=20, decimal_places=16)
    sequencing_saturation = models.DecimalField(
        max_digits=20, decimal_places=16)
    q30_bases_in_barcode = models.DecimalField(
        max_digits=20, decimal_places=16)
    q30_bases_in_rna_read = models.DecimalField(
        max_digits=20, decimal_places=16)
    q30_bases_in_sample_index = models.DecimalField(null=True, blank=True,
                                                    max_digits=20, decimal_places=16)
    q30_bases_in_UMI = models.DecimalField(max_digits=20, decimal_places=16)
    reads_mapped_to_genome = models.DecimalField(
        max_digits=20, decimal_places=16)
    reads_mapped_confidently_to_genome = models.DecimalField(
        max_digits=20, decimal_places=16)
    reads_mapped_confidently_to_intergenic_regions = models.DecimalField(
        max_digits=20, decimal_places=16)
    reads_mapped_confidently_to_intronic_regions = models.DecimalField(
        max_digits=20, decimal_places=16)
    reads_mapped_confidently_to_exonic_regions = models.DecimalField(
        max_digits=20, decimal_places=16)
    reads_mapped_confidently_to_transcriptome = models.DecimalField(
        max_digits=20, decimal_places=16)
    reads_mapped_antisense_to_gene = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_reads_in_cells = models.DecimalField(max_digits=20, decimal_places=16)
    total_genes_detected = models.PositiveIntegerField()
    median_UMI_counts_per_cell = models.PositiveIntegerField()


class TenxqcInfo(models.Model):
    annotated_cells = models.PositiveIntegerField()
    bc_q30_bases_fract = models.DecimalField(max_digits=20, decimal_places=16)
    cellranger_atac_version = models.CharField(max_length=10)
    cells_detected = models.PositiveIntegerField()
    frac_cut_fragments_in_peaks = models.DecimalField(
        max_digits=20, decimal_places=16, null=True, blank=True)
    frac_fragments_nfr = models.DecimalField(max_digits=20, decimal_places=16)
    frac_fragments_nfr_or_nuc = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_fragments_nuc = models.DecimalField(max_digits=20, decimal_places=16)
    frac_fragments_overlapping_peaks = models.DecimalField(
        max_digits=20, decimal_places=16, null=True, blank=True)
    frac_fragments_overlapping_targets = models.DecimalField(
        max_digits=20, decimal_places=16, null=True, blank=True)
    frac_mapped_confidently = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_waste_chimeric = models.DecimalField(max_digits=20, decimal_places=16)
    frac_waste_duplicate = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_waste_lowmapq = models.DecimalField(max_digits=20, decimal_places=16)
    frac_waste_mitochondrial = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_waste_no_barcode = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_waste_non_cell_barcode = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_waste_overall_nondup = models.DecimalField(
        max_digits=20, decimal_places=16)
    frac_waste_total = models.DecimalField(max_digits=20, decimal_places=16)
    frac_waste_unmapped = models.DecimalField(max_digits=20, decimal_places=16)
    median_fragments_per_cell = models.DecimalField(
        max_digits=30, decimal_places=16, null=True, blank=True)
    num_fragments = models.PositiveIntegerField()
    r1_q30_bases_fract = models.DecimalField(max_digits=20, decimal_places=16)
    r2_q30_bases_fract = models.DecimalField(max_digits=20, decimal_places=16)
    si_q30_bases_fract = models.DecimalField(
        max_digits=20, decimal_places=16, null=True, blank=True)
    total_usable_fragments = models.PositiveIntegerField()
    tss_enrichment_score = models.DecimalField(
        max_digits=20, decimal_places=16)


class SingleCellObject(models.Model):
    seqinfo = models.ForeignKey(
        'masterseq_app.SeqInfo', on_delete=models.CASCADE, blank=False, null=True)
    cooladminsubmission = models.ForeignKey(
        CoolAdminSubmission, null=True, blank=True, on_delete=models.CASCADE)
    qc_metrics = GenericForeignKey('content_type', 'object_id')
    experiment_type = models.CharField(max_length=10)
    date_last_modified = models.DateField(blank=True, null=True)
    tenx_pipeline_status = models.CharField(
        max_length=20, default='ClickToSubmit')
    path_to_websummary = models.CharField(max_length=100, blank=True)
    random_string_link = models.CharField(max_length=100, blank=True)
    # generic type foriegn key fields
    content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    object_id = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.seqinfo)

singlecell_app/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from django.db import models
from masterseq_app.models import SeqInfo, GenomeInfo, RefGenomeInfo
from .models import CoolAdminSubmission

class CoolAdminForm(ModelForm):
    refgenome = forms.ChoiceField(choices = [])
    
    def __init__(self, *args, **kwargs):
        self.spec = kwargs.pop("spec", None)
        super(CoolAdminForm, self).__init__(*args, **kwargs)
        if self.spec:
            self.fields['refgenome'] = forms.ChoiceField(label='Reference Genome',
            choices=[(x.genome_name, x.genome_name) for x in GenomeInfo.objects.filter(species=self.spec)])
    class Meta:
        model = CoolAdminSubmission
        exclude = ['seqinfo','submitted','link']
            

templates/singlecell_app/base.html
{% extends 'common/base.html' %}
{% block title %}
<title>Single Cell App</title>
{% endblock %}


{% block sidebar %}
<div id="sidebar" class="col-sm-2 col-md-2 col-lg-2" role="navigation">
    <div class="list-group navsiebar">
        <li class="sidebar-header">Single Cell App</li>
        <a href="{% url 'singlecell_app:myseqs' %}" class="list-group-item list-group-item-action-custom-gold">
            My Sequences
        </a>
        <a href="{% url 'singlecell_app:allseqs' %}" class="list-group-item list-group-item-action-custom-gold">
            All Sequences
        </a>
    </div>
</div>
{% endblock %}

{% block content %}
{% endblock %}

templates/singlecell_app/collabbase.html
{% extends 'collaborator_app/collab_base.html' %}

{% block title %}
<title>SingleCell App</title>
{% endblock %}

{% block sidebar %}
<div id="sidebar" class="col-sm-2 col-md-2 col-lg-2" role="navigation">
    <div class="list-group navsiebar">
        <li class="sidebar-header">Single Cell App</li>
        <a href="{% url 'collaborator_app:myseqs' %}" class="list-group-item list-group-item-action-custom-gold">
            My Sequences
        </a>
        </a>
    </div>
</div>

{% endblock %}

{% block content %}
{% endblock %}

templates/singlecell_app/editCoolAdmin.html
{% extends 'singlecell_app/base.html' %}
{% block content %}
{% load nextseq_app_tags %}
{% load singlecell_extras %}
<div>
    <div id="form-content">
        <h1>CoolAdmin Submission Parameters</h1>
        <div class="card">
            <div class="card-header">
                <h3>Sequence: {{seq}} </h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p }}
                    <button type="submit" url="(% url 'singlecell_app:submitcooladmin' %)" class="btn btn-primary mt-2"
                        id="save-ca-edit">
                        Save
                    </button>
                </form>
            </div>
            </card>
        </div>

    </div>
    {%endblock%}

templates/singlecell_app/myseqs.html
{% extends 'singlecell_app/base.html' %}
{% load nextseq_app_tags %}
{% load singlecell_extras %}
{% block content %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active linkblue" data-toggle="tab" href="#allScSeq" role="tab">All Sequences</a>
        </li>
        <li class="nav-item">
            <a class="nav-link linkblue" data-toggle="tab" href="#allScAtacQC" role="tab">10xATAC QC</a>
        </li>
        <li class="nav-item">
            <a class="nav-link linkblue" data-toggle="tab" href="#allScRnaQC" role="tab">10xRNA QC</a>
        </li>
        <li class="ml-auto rpadding-2">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle linkblue" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-download"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'masterseq_app:user_metadata_save_excel' %}">Save My Metadata to Excel</a>
                </div>
            </li>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="allScSeq" role="tabpanel">
            <div class="card-body">
                {% if AllSeq and BioUser %}
                <table id="datatable-user-sc" data-href="{% url 'singlecell_app:all_singlecell_data' %}"
                class="table table-striped table-sm text-center table-responsive-xl" width="100%">
                {% elif AllSeq and not BioUser %}
                <table id="datatable-all-sc" data-href="{% url 'singlecell_app:all_singlecell_data' %}"
                class="table table-striped table-sm text-center table-responsive-xl" width="100%">
                {% else %}
                <table id="datatable-user-sc" data-href="{% url 'singlecell_app:user_singlecell_data' %}"
                class="table table-striped table-sm text-center table-responsive-xl" width="100%">
                {% endif %}
                    <thead>
                        <tr>
                            <th scope="col">Sequence</th>
                            <th scope="col">Sample Info</th>
                            <th scope="col">Experiment Type</th>
                            <th scope="col">Species</th>
                            <th scope="col">Last Modified</th>
                            <th scope="col">Sequence Status</th>
                            <th scope="col">10x Pipeline Status</th>
                            <th scope="col">CoolAdmin Status</th>
                            <th scope="col">CoolAdmin Edit</th>
                            <th scope="col">Group</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>

        <div class="tab-pane fade" id="allScAtacQC" role="tabpanel">
            <div class="card-body">
                <table id="datatable-all-scATACqc" data-href="{% url 'singlecell_app:all_10xATAC_QC_data' %}"
                class="table table-striped table-sm text-center table-responsive-xl" width="100%">
                    <thead>
                        <tr>
                            <th scope="col">Sequence</th>
                            <th scope="col">Sample</th>
                            <th scope="col">Estimated Nuclei</th>
                            <th scope="col">Total fragments</th>
                            <th scope="col">Fragments per Nucleus</th>                            
                            <th scope="col">Frac of duplicates</th>
                            <th scope="col">Mitochondrial frac</th>
                            <th scope="col">TSS enrichment</th>
                            <th scope="col">CellRanger output link</th>
                            <th scope="col">Group</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        
        <div class="tab-pane fade" id="allScRnaQC" role="tabpanel">
            <div class="card-body">
                <table id="datatable-all-scRNAqc" data-href="{% url 'singlecell_app:all_10xRNA_QC_data' %}"
                class="table table-striped table-sm text-center table-responsive-xl" width="100%">
                    <thead>
                        <tr>
                            <th scope="col">Library</th>
                            <th scope="col">Sample</th>
                            <th scope="col">Estimated Cells</th>
                            <th scope="col">Total reads</th>
                            <th scope="col">Seq. Saturation</th>
                            <th scope="col">Reads per cell</th>
                            <th scope="col">Genes per cell</th>
                            <th scope="col">Fraction reads in cell</th>
                            <th scope="col">CellRanger output link</th>
                            <th scope="col">Group</th>                            
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

</div>
<div>
    <!-- pop overlay to display misc. items-->
    <!--Creates the popup body-->
    <div class="popup-overlay">
        <!--Creates the popup content-->
        <div class="popup-content">
            <h3>Confirm Reference Option</h3>
            <form class="refgenomes">
            </form>
            <button class="btn btn-md btn-primary m-3 runsinglecell-confirm">Confirm</button>
            <button class="btn btn-md btn-primary m-3 closePopup">Close</button>
        </div>
    </div>
</div>

{% endblock content %}

templates/singlecell_app/myseqs_collab.html
{% extends 'singlecell_app/collabbase.html' %}
{% load nextseq_app_tags %}
{% load singlecell_extras %}

{% block content %}

<div id="content" class="col-sm-10 col-md-10 col-lg-10">
    <div class="card">
        <div class="card-header fortable">
            {{ type }}
        </div><!-- /.card-header -->
        <div class="card-body">
            <table id="datatable-collab-sc" data-href="{% url 'collaborator_app:get_seqs' %}"
                class="table table-striped table-sm text-center table-responsive-xl">
                <thead>
                    <tr>
                        <th scope="col">Sequence</th>
                        <th scope="col">Sample Info</th>
                        <th scope="col">Experiment Type</th>
                        <th scope="col">Species</th>
                        <th scope="col">Last Modified</th>
                        <th scope="col">Sequence Status</th>
                        <th scope="col">10x Pipeline Status</th>
                        <th scope="col">CoolAdmin Status</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<div>
</div>
</div>


{% endblock content %}

templates/singlecell_app/scIndex.html
{% extends 'singlecell_app/base.html' %}
{% load singlecell_extras %}
{% block content %}
{% load nextseq_app_tags %}
<div id="content" class="col-sm-10 col-md-10 col-lg-10">
    <div class="card">
        <div class="card-header fortable">
            {{ type }}
        </div><!-- /.card-header -->
        <div class="card-body">
            <table id="datatabledetailnotes" class="table table-striped table-sm text-center table-responsive-xl">
                <thead>
                    <tr>
                        {% for head in header %}
                        <th> {{ head.0 }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                {% for library in library_lists %}
                <tr>
                    {% for head in header  %}
                    <td>

                        {{ library|tuple_do:head }}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>


{% endblock content %}